version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10-browsers

jobs:
  ui-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Node dependencies for UI tests
          command: |
            cd MyStoreUI_Test
            npm install

      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - run:
          name: Check Chrome & Chromedriver versions
          command: |
            google-chrome --version || google-chrome-stable --version
            chromedriver --version || echo "chromedriver version check failed"

      - run:
          name: Debug Nightwatch config and page objects
          command: |
            cd MyStoreUI_Test
            ls -la
            pwd
            cat nightwatch.conf.js

      - run:
          name: Run homepage search tests
          command: |
            cd MyStoreUI_Test
            npx nightwatch tests/homepageSearchTest.js || true

      - run:
          name: Run contact us tests
          command: |
            cd MyStoreUI_Test
            npx nightwatch tests/contactUsTest.js --config nightwatch.conf.js

  api-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Clone mock-user-auth
          command: |
            git clone https://github.com/thiagoluiznunes/mock-user-auth server

      - run:
          name: Install dependencies for mock-user-auth
          command: |
            cd server
            npm install
      - run:
          name: Start mock-user-auth server
          command: |
            rm -rf server
            git clone https://github.com/thiagoluiznunes/mock-user-auth server
            cd server
            npm install
            npm run dev &
            sleep 5
      - run:
          name: Install Node dependencies for API tests
          command: |
            cd my-auth-API_tests
            npm install
      - run:
          name: Check server status
          command: |
            curl -I http://localhost:3000 || echo "Server not running"
      - run:
          name: Check mock-user-auth API route
          command: |
            curl -i -X POST http://localhost:3000/api/user -H "Content-Type: application/json" -d '{"name":"Yara","password":"123"}'
      - run:
          name: Run API tests
          environment:
            BASE_URL: http://localhost:3000
          command: |
            cd my-auth-API_tests
            npx mocha test/auth.test.js --reporter mochawesome

workflows:
  version: 2
  build-and-test:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
