  api-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Node dependencies for API tests
          command: |
            cd my-auth-API_tests
            npm install

      - run:
          name: Clone and install mock-user-auth server
          command: |
            git clone https://github.com/thiagoluiznunes/mock-user-auth.git server
            cd server
            npm install

      - run:
          name: Start mock-user-auth server in background
          command: |
            cd server
            nohup npm run dev > ../server.log 2>&1 &
            echo "Server started"

      - run:
          name: Wait for server to be ready
          command: |
            echo "Waiting for server to start..."
            for i in {1..15}; do
              sleep 2
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/v1/users || true)
              echo "Attempt $i: Status $STATUS"
              if [ "$STATUS" = "200" ] || [ "$STATUS" = "403" ]; then
                echo "Server is up with status $STATUS."
                break
              fi
              if [ "$i" -eq 15 ]; then
                echo "Server did not start successfully."
                exit 1
              fi
            done

      - run:
          name: Run API tests
          command: |
            cd my-auth-API_tests
            BASE_URL=http://localhost:3000 npx mocha test/auth.test.js --reporter mochawesome

      - run:
          name: Print mock-user-auth server logs
          command: |
            echo "Server logs:"
            cat server.log || true
