version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10-browsers # ✅ Includes Chrome & Chromedriver pre-installed

jobs:
  ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node dependencies for UI tests
          command: |
            cd MyStoreUI_Test
            npm install
      - run:
          name: Check Chrome & Chromedriver versions
          command: |
            google-chrome --version || google-chrome-stable --version
            chromedriver --version || echo "chromedriver version check failed"
      - run:
          name: Run homepage search tests
          command: |
            cd MyStoreUI_Test
            npx nightwatch tests/homepageSearchTest.js
      - run:
          name: Run contact us tests
          command: |
            cd MyStoreUI_Test
            npx nightwatch tests/contactUsTest.js

  api-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node dependencies for API tests
          command: |
            cd my-auth-API_tests
            npm install
      - run:
          name: Run API tests
          command: |
            cd my-auth-API_tests
            npx mocha test/auth.test.js --reporter mochawesome

workflows:
  version: 2
  build-and-test:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
